package org.example.oopjavagroupproject.model;

import java.time.LocalDate;

/**
 * Represents a contract for a student's accommodation in a room. This class
 * corresponds to a single row in the "contracts" table in the database.
 *
 * @author Bohdan Dmytrenko, Bohdan Ruban, Olha Sribna
 * @version 1.0
 */
public class Contract {
    private int id;
    private Student student;
    private Room room;
    private LocalDate startDate;
    private LocalDate endDate;
    private String status;

    /**
     * Constructs a new Contract with a specified ID (for existing contracts).
     *
     * @param id        The unique identifier of the contract.
     * @param student   The student associated with the contract.
     * @param room      The room associated with the contract.
     * @param startDate The start date of the contract.
     * @param endDate   The end date of the contract.
     * @param status    The status of the contract (e.g., "Active", "Expired").
     */
    public Contract(int id, Student student, Room room, LocalDate startDate, LocalDate endDate, String status) {
        this.id = id;
        this.student = student;
        this.room = room;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }

    /**
     * Constructs a new Contract without a specified ID (for new contracts).
     * The ID is expected to be auto-generated by the database.
     *
     * @param student   The student associated with the contract.
     * @param room      The room associated with the contract.
     * @param startDate The start date of the contract.
     * @param endDate   The end date of the contract.
     * @param status    The status of the contract.
     */
    public Contract(Student student, Room room, LocalDate startDate, LocalDate endDate, String status) {
        this.student = student;
        this.room = room;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }

    /**
     * Returns the contract's unique ID.
     * @return The contract ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the contract's unique ID.
     * @param id The new contract ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the Student object associated with this contract.
     * @return The student.
     */
    public Student getStudent() {
        return student;
    }

    /**
     * Sets the Student object for this contract.
     * @param student The new student.
     */
    public void setStudent(Student student) {
        this.student = student;
    }

    /**
     * Returns the Room object associated with this contract.
     * @return The room.
     */
    public Room getRoom() {
        return room;
    }

    /**
     * Sets the Room object for this contract.
     * @param room The new room.
     */
    public void setRoom(Room room) {
        this.room = room;
    }

    /**
     * Returns the start date of the contract.
     * @return The start date.
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the start date of the contract.
     * @param startDate The new start date.
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the end date of the contract.
     * @return The end date.
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the end date of the contract.
     * @param endDate The new end date.
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * Returns the status of the contract.
     * @return The contract status.
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the status of the contract.
     * @param status The new contract status.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * A convenience method to get the student ID.
     * Returns 0 if the student is not set.
     * @return The ID of the student, or 0 if null.
     */
    public int getStudentId() {
        return (student != null) ? student.getId() : 0;
    }

    /**
     * A convenience method to get the room ID.
     * Returns 0 if the room is not set.
     * @return The ID of the room, or 0 if null.
     */
    public int getRoomId() {
        return (room != null) ? room.getId() : 0;
    }
}
