package org.example.oopjavagroupproject.model;

/**
 * Represents a student entity. This class corresponds to a single row
 * in the "students" table in the database.
 * It holds information about the student's personal details and their faculty.
 *
 * @author Bohdan Dmytrenko, Bohdan Ruban, Olha Sribna
 * @version 1.0
 */
public class Student {
    private int id;
    private String fullName;
    private String gender;
    private String phone;
    private Faculty faculty;

    /**
     * Constructs a new Student with a specified ID (for existing students).
     *
     * @param id        The unique identifier of the student.
     * @param fullName  The full name of the student.
     * @param gender    The gender of the student.
     * @param phone     The phone number of the student.
     * @param faculty   The faculty the student is enrolled in.
     */
    public Student(int id, String fullName, String gender, String phone, Faculty faculty) {
        this.id = id;
        this.fullName = fullName;
        this.gender = gender;
        this.phone = phone;
        this.faculty = faculty;
    }

    /**
     * Constructs a new Student without a specified ID (for new students).
     * The ID is expected to be auto-generated by the database.
     *
     * @param fullName  The full name of the student.
     * @param gender    The gender of the student.
     * @param phone     The phone number of the student.
     * @param faculty   The faculty the student is enrolled in.
     */
    public Student(String fullName, String gender, String phone, Faculty faculty) {
        this.fullName = fullName;
        this.gender = gender;
        this.phone = phone;
        this.faculty = faculty;
    }

    /**
     * Returns the student's unique ID.
     * @return The student ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the student's unique ID.
     * @param id The new student ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the student's full name.
     * @return The full name.
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the student's full name.
     * @param fullName The new full name.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Returns the student's gender.
     * @return The gender.
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the student's gender.
     * @param gender The new gender.
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Returns the student's phone number.
     * @return The phone number.
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the student's phone number.
     * @param phone The new phone number.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Returns the Faculty object associated with the student.
     * @return The student's faculty.
     */
    public Faculty getFaculty() {
        return faculty;
    }

    /**
     * Sets the Faculty object for the student.
     * @param faculty The new faculty.
     */
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }

    /**
     * A convenience method to get the faculty ID.
     * Returns 0 if the faculty is not set.
     * @return The ID of the faculty, or 0 if null.
     */
    public int getFacultyId() {
        return (faculty != null) ? faculty.getId() : 0;
    }

    /**
     * Returns the string representation of the student, which is their full name.
     * This is useful for displaying students in UI components like ComboBox.
     * @return The student's full name.
     */
    @Override
    public String toString() {
        return fullName;
    }
}
